"""add-content-columns-notes-table

Revision ID: 121dbecf578a
Revises: f7f5d36c6dd1
Create Date: 2023-02-09 10:47:23.758552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121dbecf578a'
down_revision = 'f7f5d36c6dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('notes', sa.Column('content_plain_text', sa.String(), nullable=True))
    op.drop_column('notes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'content_plain_text')
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###
