"""update-documents-documents-table

Revision ID: 1e95571859a5
Revises: 3da2122ec8dc
Create Date: 2023-02-03 20:22:39.693948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e95571859a5'
down_revision = '3da2122ec8dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskdocuments', sa.Column('document_id', sa.Integer(), nullable=False))
    op.drop_constraint('taskdocuments_documents_id_fkey', 'taskdocuments', type_='foreignkey')
    op.create_foreign_key(None, 'taskdocuments', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('taskdocuments', 'documents_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskdocuments', sa.Column('documents_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'taskdocuments', type_='foreignkey')
    op.create_foreign_key('taskdocuments_documents_id_fkey', 'taskdocuments', 'documents', ['documents_id'], ['id'], ondelete='CASCADE')
    op.drop_column('taskdocuments', 'document_id')
    # ### end Alembic commands ###
