"""status-column-members-table

Revision ID: 3d2c875181ac
Revises: ef8d29501d79
Create Date: 2023-02-20 13:25:52.199936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2c875181ac'
down_revision = 'ef8d29501d79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'members', 'member_status', ['status'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'status')
    # ### end Alembic commands ###
