"""update-documents-table

Revision ID: 3da2122ec8dc
Revises: 929e9292bb2a
Create Date: 2023-01-25 20:02:28.145413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da2122ec8dc'
down_revision = '929e9292bb2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
