"""add-content-columns-documents-table

Revision ID: 61c148e4f2a5
Revises: c902789ec77b
Create Date: 2023-02-15 22:21:02.350664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c148e4f2a5'
down_revision = 'c902789ec77b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('documents', sa.Column('content_plain_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_plain_text')
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
