"""add-description-plain_text-milestones-table

Revision ID: 6cd9e10745d7
Revises: 903d801c21fb
Create Date: 2023-02-27 17:45:43.972192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd9e10745d7'
down_revision = '903d801c21fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('description', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('milestones', sa.Column('description_plain_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'description_plain_text')
    op.drop_column('milestones', 'description')
    # ### end Alembic commands ###
