"""delete-task-documents-table

Revision ID: 6f173cc5a6af
Revises: 1e95571859a5
Create Date: 2023-02-03 21:10:39.978116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f173cc5a6af'
down_revision = '1e95571859a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskdocuments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskdocuments',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='taskdocuments_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='taskdocuments_task_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
