"""remove-description-milestones-table

Revision ID: 903d801c21fb
Revises: f3a8929fa0bd
Create Date: 2023-02-27 17:45:13.064412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903d801c21fb'
down_revision = 'f3a8929fa0bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'description_plain_text')
    op.drop_column('milestones', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('description_plain_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
