"""create-task-documents-table

Revision ID: 929e9292bb2a
Revises: 33af8c1158c3
Create Date: 2023-01-25 17:57:15.329536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929e9292bb2a'
down_revision = '33af8c1158c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskdocuments',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('documents_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documents_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'documents_id')
    )
    op.create_table('tasknotes',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'note_id')
    )
    op.drop_table('tasknote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasknote',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='tasknote_note_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='tasknote_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tasknote_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'task_id', 'note_id', name='tasknote_pkey')
    )
    op.drop_table('tasknotes')
    op.drop_table('taskdocuments')
    # ### end Alembic commands ###
