"""create-role-table

Revision ID: 9caa9172a83b
Revises: dfb2972f3ccb
Create Date: 2023-01-25 14:21:36.931188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caa9172a83b'
down_revision = 'dfb2972f3ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('projects', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('projects_created_by_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_created_by_fkey', 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('role')
    # ### end Alembic commands ###
