"""add-description-json-column-tasks-table

Revision ID: 9efb171164f5
Revises: df7850534b50
Create Date: 2023-02-16 18:05:25.815491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efb171164f5'
down_revision = 'df7850534b50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('tasks', sa.Column('description_plain_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description_plain_text')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
