"""remove-content-column-documents-table

Revision ID: c902789ec77b
Revises: 121dbecf578a
Create Date: 2023-02-15 22:20:26.029540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c902789ec77b'
down_revision = '121dbecf578a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
