"""add-project_id-in-tasks-table

Revision ID: cebe817fd84a
Revises: 6bda86e4f7d1
Create Date: 2023-02-24 07:46:16.187328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebe817fd84a'
down_revision = '6bda86e4f7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
