"""add-project_id-task_members-table

Revision ID: e044fb60b648
Revises: 2794f0b046e5
Create Date: 2023-03-06 07:45:01.859871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e044fb60b648'
down_revision = '2794f0b046e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_members', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_members', type_='foreignkey')
    op.drop_column('task_members', 'project_id')
    # ### end Alembic commands ###
